name: Detect Changed Folders
on: [workflow_call]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            android-kotlin: android-kotlin/**
            spring-backend: spring-backend/**
            llm-backend: llm-backend/**
            next-frontend: next-frontend/**
