name: Detect Changed Folders
on: [workflow_call]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            android-kotlin: android-kotlin/**
            spring-backend: spring-backend/**
            llm-backend: llm-backend/**
            next-frontend: next-frontend/**

      - id: set-matrix
        run: |
          folders=()
          if [[ "${{ steps.filter.outputs.android-kotlin }}" == "true" ]]; then folders+=("\"android-kotlin\""); fi
          if [[ "${{ steps.filter.outputs.spring-backend }}" == "true" ]]; then folders+=("\"spring-backend\""); fi
          if [[ "${{ steps.filter.outputs.llm-backend }}" == "true" ]]; then folders+=("\"llm-backend\""); fi
          if [[ "${{ steps.filter.outputs.next-frontend }}" == "true" ]]; then folders+=("\"next-frontend\""); fi

          if [ ${#folders[@]} -eq 0 ]; then
            matrix_json="{\"folder\": []}"
          else
            matrix_json="{\"folder\": [$(IFS=,; echo "${folders[*]}")]}"
          fi

          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT
