name: CI with selective build + CodeQL

on:
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:

jobs:
  detect-changed:
    uses: ./.github/workflows/detect-changed-folders.yml
 
  build:
    needs: detect-changed
    strategy:
      matrix: ${{ fromJson(needs.detect-changed.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/build.yml
    with:
      folder: ${{ matrix.folder }}

    codeql:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changed.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin, javascript, python
          build-mode: none

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dockerize:
    needs: [build, codeql]
    uses: ./.github/workflows/dockerize.yml
    with:
      image_tag: ${{ github.sha }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: dockerize
    uses: ./.github/workflows/deploy.yml
    with:
      image_tag: ${{ github.sha }}
      terraform_dir: infra/terraform/env/dev
      ansible_dir: infra/ansible
      inventory_file: inventory/dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
