name: SAST
on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run SAST on ${{ inputs.folder }}
        run: |
          cd ${{ inputs.folder }}
          case "${{ inputs.folder }}" in
            next-frontend)
              npx eslint . --ext .js,.ts,.tsx
              ;;
            spring-backend)
              ./mvnw spotbugs:check
              ;;
            android-kotlin)
              ./gradlew detekt
              ;;
            llm-backend)
              bandit -r .
              ;;
          esac
